name: Deploy
on:
  release:
    types: [published, prereleased]
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-react.yml@master
    with:
      working_directory: "./FE-CreeperKeeper"
      s3_bucket: "creeperkeeper.com"
      node_version: 20
    secrets:
      AWS_ACCOUNT_ID_PROD: ${{secrets.AWS_ACCOUNT_ID_PROD}}
      AWS_ACCOUNT_ID_DEV: ${{secrets.AWS_ACCOUNT_ID_DEV}}
