name: Deploy
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
jobs:
  deploy_react:
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-react.yml@master
    with:
      working_directory: "./FE-CreeperKeeper"
      s3_bucket: "creeperkeeper.com"
      node_version: 20
    secrets: inherit
  fetch_lambdas:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Fetch Lambda Names and Go Versions
        id: fetch_lambdas
        run: |
          chmod +x ./fetch-lambdas.sh
          lambdas=$(./fetch-lambdas.sh)
          echo "::set-output name=lambdas::$lambdas"
      - name: Set up Matrix
        id: set-matrix
        run: |
          lambdas="${{ steps.fetch_lambdas.outputs.lambdas }}"
          echo "lambdas=${lambdas}"
          matrix=$(echo "${lambdas}" | jq -r '[.[] | {name: .name, go_version: .go_version}] | tojson')
          echo "::set-output name=matrix::$matrix"
  deploy_lambdas:
    needs: fetch_lambdas
    strategy:
      matrix: ${{ fromJson(needs.fetch_lambdas.outputs.matrix) }}
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-given-version-lambda.yml@master
    with:
      version_tag: ${{ github.ref }}
      lambda_name: ${{ matrix.name }}
      runtime_version: ${{ matrix.go_version }}
      subdirectory: "./BE-CreeperKeeper/functions"
    secrets: inherit
