name: Deploy
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
jobs:
  deploy_react:
    uses: hnucamendi/shared-gha-workflows/.github/workflows/deploy-react.yml@master
    with:
      working_directory: "./FE-CreeperKeeper"
      s3_bucket: "www.creeperkeeper.com"
      cloudfront_distribution_id: "EKI8FX9WU1KYO"
      node_version: 20
    secrets: inherit
